Update patch set 1
Patch Set 1:

> oddly, building this rule normally prints a bunch of errors that
 > look like they would be fixed by this patch:
 > external/apache-http/../../frameworks/base/core/java/android/net/http/SslCertificate.java:19:
 > error: cannot find symbol
 > import com.android.internal.util.HexDump;
 > ^
 > symbol:   class HexDump
 > location: package com.android.internal.util
 > 
 > But make still thinks the rule completed successfully.  Is there a
 > problem with the return code of droiddoc?

I think these should be printed as warning instead of error,
because the missing symbols aren't really exposed in the generated docs or stub java files; They are just referenced by hidden stuff.
As far as I can tell, the error message is printed by javadoc and doclava doesn't have control.

Patch-set: 1