Update patch set 3
Patch Set 3:

Treehugger sounds like it might be a real issue, perhaps resulting from a merge conflict / another change having happened in parallel?

error: external/apache-http/Android.bp:73:26: unrecognized property "droiddoc_option_files"

Patch-set: 3
Reviewer: Gerrit User 1103203 <1103203@85c56323-6fa9-3386-8a01-6480fb634889>